<?php

return [
    'PROJECT_STATUS_OPEN' => 1,
    'PROJECT_STATUS_CONFIRM' => 2,
    'PROJECT_STATUS_FOLLOW_UP' => 3,
    'PROJECT_STATUS_NEED_FOLLOW_UP' => 4,
    'PROJECT_STATUS_CUT' => 5,
    'PROJECT_STATUS_CLOSED' => 6,

    'PROJECT_LOG_TYPE_CREATE' => 1,
    'PROJECT_LOG_TYPE_UPDATE' => 2,
    'PROJECT_LOG_TYPE_CHANGE_SALES' => 3,
    'PROJECT_LOG_TYPE_CHANGE_STATUS' => 4,
    'PROJECT_LOG_TYPE_ADD_PROGRESS' => 5
];
